routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use FallFoundry\Scraper\Http\Controllers\CrawlController;
use FallFoundry\Scraper\Http\Controllers\CrawlTestController;

Route::group(['middleware' => 'auth'], function () {
    Route::resource('crawls', CrawlController::class);
    Route::resource('crawl-tests', CrawlTestController::class);
});

resources/views/crawl_tests/create.blade.php
@extends('layouts.app')

@section('content')
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Crawl Test</h2>

<form action="{{ route('crawl-tests.store') }}" method="POST">
    @csrf
    <select name="store">
        @foreach (config('crawling.stores') as $store)
            <option value="{{ $store->getStoreId() }}">{{ $store->getName() }}</option>
        @endforeach
    </select>
    <input type="text" name="url">
    <button type="submit">Crawl</button>
</form>

@endsection

resources/views/crawls/index.blade.php
@extends('layouts.app')

@section('content')
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Crawls</h2>

<table class="w-full whitespace-no-wrap">
    <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
            <th class="px-4 py-3">Site</th>
            <th class="px-4 py-3">Status</th>
            <th class="px-4 py-3">Started</th>
            <th class="px-4 py-3">Ended</th>
            <th class="px-4 py-3">Duration</th>
            <th class="px-4 py-3"></th>
        </tr>
    </thead>
    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        @foreach ($crawls as $crawl)
        <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3 text-sm">
                {{ $crawl->store_id }}
            </td>
            <td class="px-4 py-3 text-sm">
                @php
                    $running = '';
                    $processResult = posix_getpgid($crawl->pid);
                    if ($processResult != false) {
                        $cmd = trim(file_get_contents("/proc/$crawl->pid/cmdline"), "\0");
                        if (\Illuminate\Support\Str::startsWith($cmd, "php\x00artisan\x00crawler")) {
                            $running = 'Running';
                        }
                    }
                @endphp
                {{ $running }}
            </td>
            <td class="px-4 py-3 text-sm">
                {{ $crawl->started_at }}
            </td>
            <td class="px-4 py-3 text-sm">
                {{ $crawl->ended_at }}
            </td>
            <td class="px-4 py-3 text-sm">
                @if ($crawl->ended_at != null)
                    {{ $crawl->ended_at->diffInMinutes($crawl->started_at) }} min
                @endif
            </td>
            <td class="px-4 py-3 text-sm">
                <a href="{{ route('crawls.show', $crawl) }}">View</a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/crawls/show.blade.php
@extends('layouts.app')

@section('content')
<h2 class="mt-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Crawl of {{ $crawl->site_name }} started {{ $crawl->started_at }}</h2>
<div class="mb-6 mt-2 text-sm uppercase">{{ $urls->count() }} urls</div>

<div class="mb-6">
    {{-- <form action="{{ route('crawls.update', $crawl) }}" method="POST" class="inline-block">
        @method('PUT')
        @csrf
        <button class="text-teal-600 rounded border border-teal-600 px-3 py-2 uppercase text-xs font-bold">Restart</button>
    </form> --}}
    <form action="{{ route('crawls.destroy', $crawl) }}" method="POST" class="inline-block">
        @method('DELETE')
        @csrf
        <button class="text-red-600 rounded border border-red-600 px-3 py-2 uppercase text-xs font-bold">Delete</button>
    </form>
</div>

<table class="w-full whitespace-no-wrap">
    <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
            <th class="px-4 py-3">URL</th>
            <th class="px-4 py-3">Result</th>
            <th class="px-4 py-3">Last Crawled</th>
            <th class="px-4 py-3">Details</th>
        </tr>
    </thead>
    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        @foreach ($urls as $url)
        <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3 text-xs">
                @php
                    $urlParts = parse_url($url->url);
                    $urlString = (isset($urlParts['path']) ? $urlParts['path'] : '').(isset($urlParts['query']) ? '?'.$urlParts['query'] : '').(isset($urlParts['fragment']) ? '#'.$urlParts['fragment'] : '');
                @endphp
                {{ $urlString }}
            </td>
            <td class="px-4 py-3 text-sm">
                <span class="rounded bg-gray-300 text-white px-1 py-1 text-xs font-bold mr-1">{{ $url->attempts }}</span>
                {{ $url->result }}
            </td>
            <td class="px-4 py-3 text-sm">{{ $url->last_crawled_at }}</td>
            <td class="px-4 py-3 text-sm"><pre>{{ $url->details }}</pre></td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection